export type AccountStatus = "Active" | "Suspended" | "Deactivated";
export type LinkStatus = "Pending" | "Approved" | "Correction" | "Rejected";
export type ApplicationStatus = "Submitted" | "Under review" | "Correction" | "Approved" | "Rejected" | "Archived";
export type CredentialStatus = "Active" | "Expired" | "Revoked" | "Replaced";
export type TemplateStatus = "Active" | "Draft" | "Archived";

export type IdentityAccount = {
  id: string;
  name: string;
  phone: string;
  email: string;
  barangay: string;
  personId: string;
  verification: "Verified" | "Pending";
  status: AccountStatus;
  createdAt: string;
  lastAccess: string;
  history: string[];
};
export type ResidentLink = {
  id: string;
  accountId: string;
  accountName: string;
  personId: string;
  residentName: string;
  barangay: string;
  matchScore: number;
  requestedAt: string;
  reviewedBy: string;
  status: LinkStatus;
  reason: string;
  history: string[];
};
export type IdApplication = {
  id: string;
  accountId: string;
  personId: string;
  applicantName: string;
  barangay: string;
  kind: "New ID" | "Replacement" | "Renewal";
  status: ApplicationStatus;
  submittedAt: string;
  reviewer: string;
  templateId: string;
  reason: string;
  evidence: string[];
  history: string[];
};
export type Credential = {
  id: string;
  applicationId: string;
  personId: string;
  holderName: string;
  barangay: string;
  type: string;
  status: CredentialStatus;
  issuedAt: string;
  validUntil: string;
  token: string;
  templateId: string;
  invalidReason: string;
  history: string[];
};
export type IdElementType = "text" | "photo" | "qr" | "signature" | "logo" | "shape" | "barcode";
export type IdTemplateElement = {
  id: string;
  type: IdElementType;
  label: string;
  content: string;
  side: "front" | "back";
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize: number;
  fontWeight: number;
  color: string;
  align: "left" | "center" | "right";
  background: string;
  radius: number;
  visible: boolean;
};
export type IdTemplate = {
  id: string;
  name: string;
  description: string;
  status: TemplateStatus;
  version: number;
  orientation: "Landscape" | "Portrait";
  primaryColor: string;
  secondaryColor: string;
  updatedAt: string;
  updatedBy: string;
  elements: IdTemplateElement[];
  history: string[];
};
export type IdentityRecordKind = "account" | "link" | "application" | "credential" | "template";
